services:
  api:
    build:
      context: .
    ports:
      - ${API_PORT}:3000
    env_file:
      - .env
      - .env.docker
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - nestjs:/var/lib/postgresql/data

volumes:
  nestjs:
