services:
  api:
    build:
      context: .
    ports:
      - 3000:${API_PORT}
    env_file:
      - .env
      - .env.docker
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - nestjs:/var/lib/postgresql/data

volumes:
  nestjs:
